services:

  mysql:
    image: mysql:8.0
    container_name: coin-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD
      MYSQL_DATABASE: coin_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: coin-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data: