global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'coin-simulator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'app:8082' ]
        labels:
          env: 'prod'
          instance: 'ec2'